# Generated by Django 6.0 on 2026-02-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='start_time',
        ),
    ]
