# Generated by Django 6.0 on 2026-01-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUserRoles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member'), ('GUEST', 'Guest')], max_length=10),
        ),
    ]
