# Generated by Django 6.0 on 2026-01-18 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='customuser_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userApp.customuser'),
        ),
    ]
