# Generated by Django 6.0 on 2026-01-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_enrollment_student'),
        ('userApp', '0004_remove_student_enrolled_courses_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
