# Generated by Django 6.0 on 2025-12-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCustomUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomusermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email '),
        ),
        migrations.AlterField(
            model_name='mycustomusermodel',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mycustomusermodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
