# Generated by Django 6.0 on 2025-12-25 15:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalJournal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalBlog',
            new_name='Journal',
        ),
    ]
