# Generated by Django 6.0 on 2025-12-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalJournal', '0002_rename_personalblog_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
