# Generated by Django 6.0 on 2025-12-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalJournal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
