# Generated by Django 6.0 on 2025-12-27 12:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalJournal', '0002_journalentry_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JournalEntry',
            new_name='Journal',
        ),
    ]
